version: "3"
services:
  redis:
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: martinnord
      POSTGRES_DB: devblog
  web:
    image: node:8-alpine
    command: "node /app/dist/index.js"
    volumes:
      - ".:/app"
    working_dir: "/app"
    depends_on:
      - "db"
    ports:
      - 3010:3010
    environment:
      DB_PASSWORD: password
      DB_USER: martinnord
      DB_NAME: devblog
      DB_HOST: db
      REDIS_HOST: redis
networks:
  webnet:
